name = "FG Breaks Texture Banks 01"

[[banks]]
target = "A"
source = "Vinyl Drums/Big Break Kit/Big Break Kit.xpm"
bank = "A"
label = "Vinyl Drums Big Break"

[[banks]]
target = "B"
source = "Vinyl Drums/Hand Break Kit/Hand Break Kit.xpm"
bank = "A"
label = "Vinyl Drums Hand Break"

[[banks]]
target = "C"
source = "Drumtrax/Kit 1/Kit 1.xpm"
bank = "A"
label = "Drumtrax Kit 1"

[[banks]]
target = "D"
source = "Drumulator/Clean Kit/Clean Kit.xpm"
bank = "A"
label = "Drumulator Clean"

[[banks]]
target = "E"
source = "LM-1/Computer Love Kit/Computer Love Kit.xpm"
bank = "A"
label = "LM-1 Computer Love"

[[banks]]
target = "F"
source = "Found Sounds/Body Kit/Body Kit.xpm"
bank = "A"
label = "Found Sounds Body Kit A"

[[banks]]
target = "G"
source = "S950 Snacks/Club 8 Kit/Club 8 Kit.xpm"
bank = "A"
label = "S950 Club 8"

[[banks]]
target = "H"
source = "S950 Snacks/Hard Glitch Kit/Hard Glitch Kit.xpm"
bank = "A"
label = "S950 Hard Glitch"
