"""Render a self-contained browser review companion for a creative wave."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


def review_data(report: dict[str, Any]) -> dict[str, Any]:
    candidates = report.get("candidates")
    if report.get("kind") != "mpc-workstation-wave" or not isinstance(candidates, list):
        raise ValueError("creative review requires an mpc-workstation-wave report")
    if not candidates:
        raise ValueError("creative review requires at least one candidate")
    compact = []
    for item in candidates:
        required = {
            "rank", "id", "family", "seed", "name", "tempo", "key", "scale", "bars",
            "score", "metrics", "suggested_programs", "paths", "preview",
        }
        if not isinstance(item, dict) or not required.issubset(item):
            raise ValueError("creative wave candidate is missing review fields")
        compact.append({key: item[key] for key in (
            "rank", "id", "family", "seed", "name", "tempo", "key", "scale", "bars",
            "score", "metrics", "suggested_programs", "paths", "preview",
        )})
    identity = [
        (item["id"], item["family"], item["seed"], item["score"]["exploration_score"])
        for item in compact
    ]
    fingerprint = hashlib.sha256(
        json.dumps(identity, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()[:16]
    return {
        "schema_version": 1,
        "kind": "mpc-creative-wave-review",
        "title": report.get("name", "MPC Creative Wave Review"),
        "fingerprint": fingerprint,
        "ranking_policy": report.get("ranking_policy", ""),
        "hardware_status": "deferred",
        "candidates": compact,
    }


def render_html(report: dict[str, Any]) -> str:
    payload = json.dumps(review_data(report), separators=(",", ":")).replace("</", "<\\/")
    return HTML_TEMPLATE.replace("__DATA__", payload)


def build_review(report_path: Path, output: Path, *, force: bool = False) -> Path:
    report_path = report_path.expanduser().resolve()
    output = output.expanduser().resolve()
    if output.exists() and not force:
        raise FileExistsError(f"creative review exists: {output}")
    report = json.loads(report_path.read_text(encoding="utf-8"))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_html(report), encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wave", type=Path, help="wave.json generated by mpc-workstation-wave")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--force", action="store_true", help="replace only the named HTML file")
    args = parser.parse_args(argv or sys.argv[1:])
    output = build_review(args.wave, args.output, force=args.force)
    print(f"Wrote: {output}")
    print("Browser capabilities: filter, compare, local notes, and JSON/CSV shortlist export")
    print("Hardware and musical-quality status remain deferred.")
    return 0


HTML_TEMPLATE = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>MPC Creative Wave Review</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color-scheme:dark;--bg:#0b0e12;--panel:#141922;--line:#2a3342;--text:#f2f5fa;--muted:#9aa7b9;--cyan:#74dbe8;--pink:#f28cc6;--green:#91e6ad;--amber:#f4ca6e;--red:#ff867f}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% -20%,#223348 0,transparent 42rem),var(--bg);color:var(--text)}button,select,textarea{font:inherit}button{cursor:pointer}.shell{max-width:1500px;margin:auto;padding:28px clamp(14px,4vw,54px) 70px}.eyebrow{color:var(--cyan);font-weight:800;letter-spacing:.14em;text-transform:uppercase;font-size:.72rem}h1{font-size:clamp(2.2rem,6vw,5rem);line-height:.92;letter-spacing:-.055em;margin:10px 0 14px}.lede{max-width:830px;color:var(--muted);line-height:1.55}.toolbar{display:flex;flex-wrap:wrap;gap:9px;margin:25px 0}.toolbar select,.toolbar button,.file{border:1px solid var(--line);background:#161d28;color:var(--text);border-radius:10px;padding:9px 12px}.file input{display:none}.summary{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.pill{border:1px solid var(--line);border-radius:999px;padding:6px 10px;color:#c7d1df;font-size:.8rem}.layout{display:grid;grid-template-columns:minmax(330px,.82fr) minmax(480px,1.18fr);gap:18px}.panel{background:#111720dd;border:1px solid var(--line);border-radius:18px;padding:16px}.list{display:grid;gap:8px;max-height:72vh;overflow:auto}.candidate{display:grid;grid-template-columns:1fr auto;gap:8px;text-align:left;width:100%;border:1px solid transparent;background:#171e29;color:var(--text);padding:12px;border-radius:12px}.candidate:hover{border-color:#43526a}.candidate.active{border-color:var(--cyan);background:#1b2835}.candidate small{display:block;color:var(--muted);margin-top:4px}.score{font-size:1.35rem;color:var(--cyan);font-weight:800}.detail-head{display:flex;justify-content:space-between;gap:15px}.detail h2{margin:3px 0;font-size:1.8rem}.meta{color:var(--muted)}.status{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:18px 0}.status button{border:1px solid var(--line);background:#171e29;color:var(--text);padding:9px;border-radius:9px}.status button.active{border-color:var(--cyan);background:#203545}.charts{display:grid;gap:12px}.chart{border:1px solid var(--line);border-radius:13px;padding:12px;background:#0d1219}.chart h3{font-size:.85rem;margin:0 0 9px;color:#cdd7e5}.roll{position:relative;height:170px;background:repeating-linear-gradient(to right,#ffffff08 0,#ffffff08 1px,transparent 1px,transparent 6.25%),linear-gradient(#151c26,#10151d);overflow:hidden;border-radius:7px}.note{position:absolute;min-width:3px;border-radius:3px;background:var(--pink);opacity:.88}.note.bass{background:var(--cyan)}.note.chords{background:#a99af3}.drums{display:grid;grid-template-columns:90px repeat(16,1fr);gap:3px;align-items:center}.role{font-size:.68rem;color:var(--muted);overflow:hidden}.cell{aspect-ratio:1;border-radius:3px;background:#1b2531}.cell.on{background:var(--green)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:14px 0}.metric{background:#0d1219;border-radius:9px;padding:8px}.metric span{display:block;color:var(--muted);font-size:.68rem;text-transform:uppercase}.metric b{font-size:.9rem}.programs{font-size:.8rem;color:var(--muted);line-height:1.5}.notes{width:100%;min-height:85px;resize:vertical;border:1px solid var(--line);background:#0d1219;color:var(--text);border-radius:10px;padding:10px;margin-top:8px}.compare{margin-top:18px}.compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.compare-card{border:1px solid var(--line);border-radius:10px;padding:10px;background:#0d1219}.compare-card b{display:block}.compare-card small{color:var(--muted)}.boundary{color:var(--muted);font-size:.78rem;line-height:1.5;margin-top:15px}@media(max-width:900px){.layout{grid-template-columns:1fr}.list{max-height:340px}}@media(max-width:600px){.shell{padding:20px 10px 50px}.metrics{grid-template-columns:1fr 1fr}.drums{grid-template-columns:75px repeat(16,12px);overflow:auto}.status{grid-template-columns:1fr 1fr}}
  </style>
</head>
<body><main class="shell">
  <div class="eyebrow">Offline candidate lab</div><h1 id="title"></h1>
  <p class="lede">Compare reproducible MIDI candidates before loading them on the MPC. Scores describe observable variation and complexity; they are not judgments of musical quality.</p>
  <div class="toolbar"><select id="family" aria-label="Filter family"></select><select id="verdict" aria-label="Filter verdict"><option value="all">All verdicts</option><option>pending</option><option>keep</option><option>provisional</option><option>reject</option></select><button id="export-json">Export JSON</button><button id="export-csv">Export CSV</button><label class="file">Import JSON<input id="import" type="file" accept="application/json"></label><button id="reset">Reset local notes</button></div>
  <div class="summary" id="summary"></div>
  <div class="layout"><section class="panel"><div class="list" id="list"></div></section><section class="panel detail" id="detail"></section></div>
</main>
<script>
const DATA=__DATA__,STATUSES=['pending','keep','provisional','reject'],KEY='mpc-creative-review:'+DATA.fingerprint;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function fresh(){return{fingerprint:DATA.fingerprint,items:Object.fromEntries(DATA.candidates.map(c=>[c.id,{status:'pending',notes:''}]))}}
function merge(v){const n=fresh();if(v?.fingerprint!==DATA.fingerprint)return n;for(const [id,x] of Object.entries(v.items||{}))if(n.items[id]){n.items[id].status=STATUSES.includes(x.status)?x.status:'pending';n.items[id].notes=typeof x.notes==='string'?x.notes:''}return n}
function load(){try{return merge(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return fresh()}}
let state=load(),selected=DATA.candidates[0]?.id;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function candidate(){return DATA.candidates.find(c=>c.id===selected)||DATA.candidates[0]}
function filtered(){return DATA.candidates.filter(c=>($('family').value==='all'||c.family===$('family').value)&&($('verdict').value==='all'||state.items[c.id].status===$('verdict').value))}
function setup(){document.title=DATA.title;$('title').textContent=DATA.title;const families=[...new Set(DATA.candidates.map(c=>c.family))];$('family').innerHTML='<option value="all">All families</option>'+families.map(x=>`<option>${esc(x)}</option>`).join('');$('family').onchange=render;$('verdict').onchange=render}
function render(){const rows=filtered();if(!rows.some(c=>c.id===selected))selected=rows[0]?.id||DATA.candidates[0]?.id;$('summary').innerHTML=`<span class="pill">${DATA.candidates.length} candidates</span><span class="pill">${new Set(DATA.candidates.map(c=>c.family)).size} families</span><span class="pill">${Object.values(state.items).filter(x=>x.status==='keep').length} kept</span><span class="pill">hardware ${DATA.hardware_status}</span>`;$('list').innerHTML=rows.map(c=>`<button class="candidate ${c.id===selected?'active':''}" data-id="${esc(c.id)}"><span><b>${esc(c.name)} · seed ${c.seed}</b><small>${esc(c.family)} · ${c.tempo} BPM · ${esc(c.key)} ${esc(c.scale)} · ${esc(state.items[c.id].status)}</small></span><span class="score">${c.score.exploration_score}</span></button>`).join('')||'<p class="meta">No candidates match this filter.</p>';$('list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()});renderDetail(candidate())}
function piano(c){const ev=c.preview.filter(e=>e.track!=='drums'),notes=ev.map(e=>e.note),lo=Math.min(...notes,48),hi=Math.max(...notes,72),ticks=c.bars*4*480;return`<div class="roll">${ev.map(e=>`<i class="note ${e.track}" title="${esc(e.track)} ${e.note}" style="left:${e.tick/ticks*100}%;width:${Math.max(.5,e.duration/ticks*100)}%;bottom:${(e.note-lo)/Math.max(1,hi-lo)*88+3}%;height:5px"></i>`).join('')}</div>`}
function drums(c){const ev=c.preview.filter(e=>e.track==='drums'),roles=[...new Set(ev.map(e=>e.role))].slice(0,8),stepTicks=c.bars*4*480/16;return`<div class="drums">${roles.map(r=>`<span class="role">${esc(r)}</span>${Array.from({length:16},(_,i)=>`<i class="cell ${ev.some(e=>e.role===r&&Math.floor(e.tick/stepTicks)%16===i)?'on':''}"></i>`).join('')}`).join('')}</div>`}
function renderDetail(c){if(!c){$('detail').innerHTML='<p class="meta">No candidate selected.</p>';return}const s=state.items[c.id],metrics=c.metrics,programs=Object.entries(c.suggested_programs).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · ');$('detail').innerHTML=`<div class="detail-head"><div><div class="eyebrow">${esc(c.family)} · seed ${c.seed}</div><h2>${esc(c.name)}</h2><div class="meta">${c.tempo} BPM · ${esc(c.key)} ${esc(c.scale)} · ${c.bars} bars</div></div><div class="score">${c.score.exploration_score}</div></div><div class="status">${STATUSES.map(x=>`<button data-status="${x}" class="${s.status===x?'active':''}">${x}</button>`).join('')}</div><div class="charts"><div class="chart"><h3>Pitched-note overview</h3>${piano(c)}</div><div class="chart"><h3>Semantic drum grid</h3>${drums(c)}</div></div><div class="metrics">${Object.entries(metrics).map(([k,v])=>`<div class="metric"><span>${esc(k.replaceAll('_',' '))}</span><b>${typeof v==='number'?Math.round(v*100)/100:esc(v)}</b></div>`).join('')}</div><div class="programs">Suggested programs · ${programs}</div><textarea class="notes" id="notes" placeholder="Listening, import, arrangement, or sound-selection notes…">${esc(s.notes)}</textarea><div class="compare"><h3>Compare candidates</h3><div class="compare-grid"><select id="compare-a"></select><select id="compare-b"></select></div><div id="comparison"></div></div><p class="boundary">Files: ${esc(c.paths.idea_midi)} and ${esc(c.paths.sequences)}. Browser state is local to this wave fingerprint. A keep verdict is a shortlist choice, not a hardware pass.</p>`;$('detail').querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{s.status=b.dataset.status;save();render()});$('notes').oninput=e=>{s.notes=e.target.value;save()};compare(c)}
function compare(c){const options=DATA.candidates.map(x=>`<option value="${esc(x.id)}">${esc(x.family)} · ${x.seed}</option>`).join(''),a=$('compare-a'),b=$('compare-b');a.innerHTML=options;b.innerHTML=options;a.value=c.id;b.value=DATA.candidates.find(x=>x.id!==c.id)?.id||c.id;const draw=()=>{const x=DATA.candidates.find(v=>v.id===a.value),y=DATA.candidates.find(v=>v.id===b.value);$('comparison').innerHTML=`<div class="compare-grid"><div class="compare-card"><b>${esc(x.name)} · ${x.seed}</b><small>score ${x.score.exploration_score} · range ${x.metrics.melody_range_semitones} · sync ${x.metrics.syncopation_percent}%</small></div><div class="compare-card"><b>${esc(y.name)} · ${y.seed}</b><small>score ${y.score.exploration_score} · range ${y.metrics.melody_range_semitones} · sync ${y.metrics.syncopation_percent}%</small></div></div>`};a.onchange=draw;b.onchange=draw;draw()}
function payload(){return{schema_version:1,kind:'mpc-creative-wave-results',fingerprint:DATA.fingerprint,exported_at:new Date().toISOString(),items:DATA.candidates.map(c=>({id:c.id,family:c.family,seed:c.seed,status:state.items[c.id].status,notes:state.items[c.id].notes}))}}
function download(name,type,text){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),0)}
$('export-json').onclick=()=>download('creative-wave-results.json','application/json',JSON.stringify(payload(),null,2)+'\n');$('export-csv').onclick=()=>{const rows=[['id','family','seed','status','notes'],...payload().items.map(x=>[x.id,x.family,x.seed,x.status,x.notes])];download('creative-wave-results.csv','text/csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')+'\n')};$('import').onchange=async e=>{try{const v=JSON.parse(await e.target.files[0].text());if(v.kind!=='mpc-creative-wave-results'||v.fingerprint!==DATA.fingerprint)throw Error('Results do not match this wave.');state=merge({fingerprint:v.fingerprint,items:Object.fromEntries(v.items.map(x=>[x.id,x]))});save();render()}catch(x){alert('Import failed: '+x.message)}e.target.value=''};$('reset').onclick=()=>{if(confirm('Reset all local verdicts and notes?')){state=fresh();save();render()}};setup();render();
</script></body></html>'''
